import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'
import Header from "./components/Header";
import ThreeScene from "./components/Three";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        {/* <Header/> */}
        {children}
      </body>
    </html>
  );
}
